### ISSUE TITLE
Package EmptyEpsilon via Flatpack and publish on Flathub

### ISSUE THREAD

**Issue by Flowdalic** [daid/EmptyEpsilon#1967]
EmptyEpsilon is a great game. Unfortunately it is not easily accessible since it is not [widely packaged](https://repology.org/project/emptyepsilon/versions).

Therefore, please consider to package `EmptyEpsilon` via Flatpack and publish it on [Flathub](https://flathub.org/). Thanks.

**Comment by pavelsinkevich** [comment]
That would be great! I want to try this game on SteamDeck, and since it's Arch Linux, .deb file doesn't help very much. With Flathub it would be as easy as just click "Install".

**Comment by daid** [comment]
`hello.sh`?

**Comment by Xansta** [comment]
That was the example application in the instructions, hello.sh. I did not try to create a manifest for Empty Epsilon, because I don't know it that well. So, yes, I did not provide comprehensive instructions, I just provided the outline, particularly the instructions directly related to Flatpack. There still needs work creating a manifest document. If you don't have the time, @daid, I was hoping someone else familiar with the package would, perhaps the people asking for the Flatpack distribution in the first place (@Flowdalic and @pavelsinkevich - I'm looking at you)

**Comment by gwaland** [comment]
So I've got a little bit to move with this yaml.  but it hangs up because I haven't figured out how to tell it where SeriousProton sources are since it is trying to build serious proton and install it first.  I had to enable teh share=network buildoption since serious proton wants glm and basis_universal packages and trying to build those first were proving problematic. 
[EmptyEpsilon-full.yaml.gz](https://github.com/daid/EmptyEpsilon/files/12566397/EmptyEpsilon-full.yaml.gz)

**Comment by gwaland** [comment]
I got it to compile with this yaml.  But I don't have a non-headless box setup to test with flatpak right now. 
```
id: org.flatpak.emptyepsilon
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
finish-args:
  - --share=network
command: EmptyEpsilon
modules:
  - name: EmptyEpsilon
    buildsystem: cmake-ninja
    build-options:
      build-args:
        - "--share=network"
    config-opts:
      - "-DSERIOUS_PROTON_DIR=./SeriousProton"
    sources:
      - type: git
        url: https://github.com/daid/EmptyEpsilon.git
      - type: git
        url: https://github.com/daid/SeriousProton.git
        dest: SeriousProton

```

**Comment by Xansta** [comment]
@oznogon tested and it built, but it did not run. Turns out permissions needed to be enabled. See [this link](https://discord.com/channels/206597597455056898/468130064513368064/1175191573206663208) for details.

```
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=fallback-x11
  # Wayland access
  - --socket=wayland
  # GPU acceleration if needed
  - --device=dri
  # Needs to talk to the network:
  - --share=network
  ```
  
  Additional parameter also suggested:
  `--socket=pulseaudio`
...to enable sound.

Thanks Oznogon

**Comment by oznogon** [comment]
Yep. To confirm, here's the verbatim manifest I used on Fedora 39, which is just @gwaland's with the extra permissions:

```yaml
id: org.flatpak.EmptyEpsilon
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=fallback-x11
  # Wayland access
  - --socket=wayland
  # GPU acceleration if needed
  - --device=dri
  # Needs to talk to the network
  - --share=network
  # Audio if needed
  - --socket=pulseaudio
command: EmptyEpsilon
modules:
  - name: EmptyEpsilon
    buildsystem: cmake-ninja
    build-options:
      build-args:
        - "--share=network"
    config-opts:
      - "-DSERIOUS_PROTON_DIR=./SeriousProton"
    sources:
      - type: git
        url: https://github.com/daid/EmptyEpsilon.git
      - type: git
        url: https://github.com/daid/SeriousProton.git
        dest: SeriousProton
```
